import {
  ArtBoard,
  Comparison,
  Compass,
  DataAnalysis,
  DeskLamp,
  DesktopOnly,
  Developing,
  Dna,
  Duplicate,
  EmptyImage,
  Fault,
  Folder,
  Labs,
  Loss,
  Map,
  NoApi,
  Nutrition,
  OutOfStock,
  PaperPlane,
  Password,
  Plug,
  Success,
  Table,
  Text,
  Verification,
  Relational,
  Report,
  SearchContent,
  Shredder,
  Startup,
  Storytelling,
  Strategy,
  WrongWay,
  RealTime,
} from './illustrationList';

export const illustrationMap = {
  'art-board': ArtBoard,
  comparison: Comparison,
  compass: Compass,
  'data-analysis': DataAnalysis,
  'desk-lamp': DeskLamp,
  'desktop-only': DesktopOnly,
  developing: Developing,
  dna: Dna,
  duplicate: Duplicate,
  'empty-image': EmptyImage,
  fault: Fault,
  folder: Folder,
  labs: Labs,
  loss: Loss,
  map: Map,
  'no-api': NoApi,
  nutrition: Nutrition,
  'out-of-stock': OutOfStock,
  'paper-plane': PaperPlane,
  password: Password,
  plug: Plug,
  relational: Relational,
  report: Report,
  'search-content': SearchContent,
  shredder: Shredder,
  startup: Startup,
  storytelling: Storytelling,
  strategy: Strategy,
  success: Success,
  table: Table,
  text: Text,
  verification: Verification,
  'wrong-way': WrongWay,
  'real-time': RealTime,
} as const;

export type IllustrationName = keyof typeof illustrationMap;
