export default [
  {
    month: 'Jan',
    units: Math.floor(Math.random() * 120),
    male: Math.floor(Math.random() * 100),
    female: Math.floor(Math.random() * 100),
    sales: Math.floor(Math.random() * 5000),
  },
  {
    month: 'Feb',
    units: Math.floor(Math.random() * 120),
    male: Math.floor(Math.random() * 100),
    female: Math.floor(Math.random() * 100),
    sales: Math.floor(Math.random() * 5000),
  },
  {
    month: 'Mar',
    units: Math.floor(Math.random() * 120),
    male: Math.floor(Math.random() * 100),
    female: Math.floor(Math.random() * 100),
    sales: Math.floor(Math.random() * 5000),
  },
  {
    month: 'Apr',
    units: Math.floor(Math.random() * 120),
    male: Math.floor(Math.random() * 100),
    female: Math.floor(Math.random() * 100),
    sales: Math.floor(Math.random() * 5000),
  },
  {
    month: 'May',
    units: Math.floor(Math.random() * 120),
    male: Math.floor(Math.random() * 100),
    female: Math.floor(Math.random() * 100),
    sales: Math.floor(Math.random() * 5000),
  },
  {
    month: 'Jun',
    units: Math.floor(Math.random() * 120),
    male: Math.floor(Math.random() * 100),
    female: Math.floor(Math.random() * 100),
    sales: Math.floor(Math.random() * 5000),
  },
  {
    month: 'Jul',
    units: Math.floor(Math.random() * 120),
    male: Math.floor(Math.random() * 100),
    female: Math.floor(Math.random() * 100),
    sales: Math.floor(Math.random() * 5000),
  },
  {
    month: 'Aug',
    units: Math.floor(Math.random() * 120),
    male: Math.floor(Math.random() * 100),
    female: Math.floor(Math.random() * 100),
    sales: Math.floor(Math.random() * 5000),
  },
  {
    month: 'Sep',
    units: Math.floor(Math.random() * 120),
    male: Math.floor(Math.random() * 100),
    female: Math.floor(Math.random() * 100),
    sales: Math.floor(Math.random() * 5000),
  },
  {
    month: 'Oct',
    units: Math.floor(Math.random() * 120),
    male: Math.floor(Math.random() * 100),
    female: Math.floor(Math.random() * 100),
    sales: Math.floor(Math.random() * 5000),
  },
  {
    month: 'Nov',
    units: Math.floor(Math.random() * 120),
    male: Math.floor(Math.random() * 100),
    female: Math.floor(Math.random() * 100),
    sales: Math.floor(Math.random() * 5000),
  },
  {
    month: 'Dec',
    units: Math.floor(Math.random() * 120),
    male: Math.floor(Math.random() * 100),
    female: Math.floor(Math.random() * 100),
    sales: Math.floor(Math.random() * 5000),
  },
];
