export default [
  {
    bin: 'A',
    bins: [
      { bin: 'January', count: Math.random() * 100 },
      { bin: 'February', count: Math.random() * 100 },
      { bin: 'March', count: Math.random() * 100 },
      { bin: 'April', count: Math.random() * 100 },
      { bin: 'May', count: Math.random() * 100 },
      { bin: 'June', count: Math.random() * 100 },
      { bin: 'July', count: Math.random() * 100 },
      { bin: 'August', count: Math.random() * 100 },
      { bin: 'September', count: Math.random() * 100 },
      { bin: 'October', count: Math.random() * 100 },
      { bin: 'November', count: Math.random() * 100 },
      { bin: 'December', count: Math.random() * 100 },
    ],
  },
  {
    bin: 'B',
    bins: [
      { bin: 'January', count: Math.random() * 100 },
      { bin: 'February', count: Math.random() * 100 },
      { bin: 'March', count: Math.random() * 100 },
      { bin: 'April', count: Math.random() * 100 },
      { bin: 'May', count: Math.random() * 100 },
      { bin: 'June', count: Math.random() * 100 },
      { bin: 'July', count: Math.random() * 100 },
      { bin: 'August', count: Math.random() * 100 },
      { bin: 'September', count: Math.random() * 100 },
      { bin: 'October', count: Math.random() * 100 },
      { bin: 'November', count: Math.random() * 100 },
      { bin: 'December', count: Math.random() * 100 },
    ],
  },
  {
    bin: 'C',
    bins: [
      { bin: 'January', count: Math.random() * 100 },
      { bin: 'February', count: Math.random() * 100 },
      { bin: 'March', count: Math.random() * 100 },
      { bin: 'April', count: Math.random() * 100 },
      { bin: 'May', count: Math.random() * 100 },
      { bin: 'June', count: Math.random() * 100 },
      { bin: 'July', count: Math.random() * 100 },
      { bin: 'August', count: Math.random() * 100 },
      { bin: 'September', count: Math.random() * 100 },
      { bin: 'October', count: Math.random() * 100 },
      { bin: 'November', count: Math.random() * 100 },
      { bin: 'December', count: Math.random() * 100 },
    ],
  },
  {
    bin: 'D',
    bins: [
      { bin: 'January', count: Math.random() * 100 },
      { bin: 'February', count: Math.random() * 100 },
      { bin: 'March', count: Math.random() * 100 },
      { bin: 'April', count: Math.random() * 100 },
      { bin: 'May', count: Math.random() * 100 },
      { bin: 'June', count: Math.random() * 100 },
      { bin: 'July', count: Math.random() * 100 },
      { bin: 'August', count: Math.random() * 100 },
      { bin: 'September', count: Math.random() * 100 },
      { bin: 'October', count: Math.random() * 100 },
      { bin: 'November', count: Math.random() * 100 },
      { bin: 'December', count: Math.random() * 100 },
    ],
  },
  {
    bin: 'E',
    bins: [
      { bin: 'January', count: Math.random() * 100 },
      { bin: 'February', count: Math.random() * 100 },
      { bin: 'March', count: Math.random() * 100 },
      { bin: 'April', count: Math.random() * 100 },
      { bin: 'May', count: Math.random() * 100 },
      { bin: 'June', count: Math.random() * 100 },
      { bin: 'July', count: Math.random() * 100 },
      { bin: 'August', count: Math.random() * 100 },
      { bin: 'September', count: Math.random() * 100 },
      { bin: 'October', count: Math.random() * 100 },
      { bin: 'November', count: Math.random() * 100 },
      { bin: 'December', count: Math.random() * 100 },
    ],
  },
  {
    bin: 'F',
    bins: [
      { bin: 'January', count: Math.random() * 100 },
      { bin: 'February', count: Math.random() * 100 },
      { bin: 'March', count: Math.random() * 100 },
      { bin: 'April', count: Math.random() * 100 },
      { bin: 'May', count: Math.random() * 100 },
      { bin: 'June', count: Math.random() * 100 },
      { bin: 'July', count: Math.random() * 100 },
      { bin: 'August', count: Math.random() * 100 },
      { bin: 'September', count: Math.random() * 100 },
      { bin: 'October', count: Math.random() * 100 },
      { bin: 'November', count: Math.random() * 100 },
      { bin: 'December', count: Math.random() * 100 },
    ],
  },
  {
    bin: 'G',
    bins: [
      { bin: 'January', count: Math.random() * 100 },
      { bin: 'February', count: Math.random() * 100 },
      { bin: 'March', count: Math.random() * 100 },
      { bin: 'April', count: Math.random() * 100 },
      { bin: 'May', count: Math.random() * 100 },
      { bin: 'June', count: Math.random() * 100 },
      { bin: 'July', count: Math.random() * 100 },
      { bin: 'August', count: Math.random() * 100 },
      { bin: 'September', count: Math.random() * 100 },
      { bin: 'October', count: Math.random() * 100 },
      { bin: 'November', count: Math.random() * 100 },
      { bin: 'December', count: Math.random() * 100 },
    ],
  },
  {
    bin: 'H',
    bins: [
      { bin: 'January', count: Math.random() * 100 },
      { bin: 'February', count: Math.random() * 100 },
      { bin: 'March', count: Math.random() * 100 },
      { bin: 'April', count: Math.random() * 100 },
      { bin: 'May', count: Math.random() * 100 },
      { bin: 'June', count: Math.random() * 100 },
      { bin: 'July', count: Math.random() * 100 },
      { bin: 'August', count: Math.random() * 100 },
      { bin: 'September', count: Math.random() * 100 },
      { bin: 'October', count: Math.random() * 100 },
      { bin: 'November', count: Math.random() * 100 },
      { bin: 'December', count: Math.random() * 100 },
    ],
  },
  {
    bin: 'I',
    bins: [
      { bin: 'January', count: Math.random() * 100 },
      { bin: 'February', count: Math.random() * 100 },
      { bin: 'March', count: Math.random() * 100 },
      { bin: 'April', count: Math.random() * 100 },
      { bin: 'May', count: Math.random() * 100 },
      { bin: 'June', count: Math.random() * 100 },
      { bin: 'July', count: Math.random() * 100 },
      { bin: 'August', count: Math.random() * 100 },
      { bin: 'September', count: Math.random() * 100 },
      { bin: 'October', count: Math.random() * 100 },
      { bin: 'November', count: Math.random() * 100 },
      { bin: 'December', count: Math.random() * 100 },
    ],
  },
  {
    bin: 'J',
    bins: [
      { bin: 'January', count: Math.random() * 100 },
      { bin: 'February', count: Math.random() * 100 },
      { bin: 'March', count: Math.random() * 100 },
      { bin: 'April', count: Math.random() * 100 },
      { bin: 'May', count: Math.random() * 100 },
      { bin: 'June', count: Math.random() * 100 },
      { bin: 'July', count: Math.random() * 100 },
      { bin: 'August', count: Math.random() * 100 },
      { bin: 'September', count: Math.random() * 100 },
      { bin: 'October', count: Math.random() * 100 },
      { bin: 'November', count: Math.random() * 100 },
      { bin: 'December', count: Math.random() * 100 },
    ],
  },
];
